FROM node:latest
# Create the directory!
RUN mkdir -p /usr/src/bot
WORKDIR /usr/src/bot
# Copy and Install our bot
COPY package.json /usr/src/bot
RUN npm install -g
RUN yarn
# Our precious bot
COPY . /usr/src/bot
# Build bot
RUN yarn build
# Run bot
SHELL [ "yarn", "start" ]
